######################################################################
#
# File name : ALU_tb_compile.do
# Created on: Fri Apr 20 18:33:37 +0800 2018
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
D:\\SoftPath\\modelsim\\win64\\vlib work
D:\\SoftPath\\modelsim\\win64\\vlib msim

D:\\SoftPath\\modelsim\\win64\\vlib msim/xil_defaultlib

D:\\SoftPath\\modelsim\\win64\\vmap xil_defaultlib msim/xil_defaultlib

D:\\SoftPath\\modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../CPU-Azathoth.srcs/sources_1/new" \
"ALU_tb_time_impl.v" \
"../../../../CPU-Azathoth.srcs/sim_1/new/ALU_tb.v" \


quit -force

