######################################################################
#
# File name : ALU_tb_simulate.do
# Created on: Fri Apr 20 18:33:40 +0800 2018
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vsim -voptargs="+acc" +transport_int_delays +pulse_r/0 +pulse_int_r/0 -L simprims_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.ALU_tb xil_defaultlib.glbl

do {ALU_tb_wave.do}

view wave
view structure
view signals

do {ALU_tb.udo}

run 2000ns
