######################################################################
#
# File name : ALU_tb_wave.do
# Created on: Fri Apr 20 18:33:40 +0800 2018
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
