######################################################################
#
# File name : ALU_tb.udo
# Created on: Fri Apr 20 18:37:33 +0800 2018
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
