######################################################################
#
# File name : computer_tb.udo
# Created on: Sat May 26 23:09:58 +0800 2018
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
