######################################################################
#
# File name : cpu_div_tb_simulate.do
# Created on: Thu Apr 26 23:26:05 +0800 2018
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vsim -voptargs="+acc" +transport_int_delays +pulse_r/0 +pulse_int_r/0 -L simprims_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.cpu_div_tb xil_defaultlib.glbl

do {cpu_div_tb_wave.do}

view wave
view structure
view signals

do {cpu_div_tb.udo}

run 1000ns
