######################################################################
#
# File name : cpu_div_tb_wave.do
# Created on: Thu Apr 26 23:26:05 +0800 2018
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
