######################################################################
#
# File name : cpu_div_tb_compile.do
# Created on: Thu Apr 26 23:26:03 +0800 2018
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
D:\\SoftPath\\modelsim\\win64\\vlib work
D:\\SoftPath\\modelsim\\win64\\vlib msim

D:\\SoftPath\\modelsim\\win64\\vlib msim/xil_defaultlib

D:\\SoftPath\\modelsim\\win64\\vmap xil_defaultlib msim/xil_defaultlib

D:\\SoftPath\\modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../CPU-Nyarlathotep.srcs/sources_1/new" \
"cpu_div_tb_time_synth.v" \
"../../../../CPU-Nyarlathotep.srcs/sim_1/new/cpu_div_tb.v" \


quit -force

