######################################################################
#
# File name : sccomp_dataflow_oj_tb_compile.do
# Created on: Thu Apr 26 02:02:41 +0800 2018
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
D:\\SoftPath\\modelsim\\win64\\vlib work
D:\\SoftPath\\modelsim\\win64\\vlib msim

D:\\SoftPath\\modelsim\\win64\\vlib msim/xil_defaultlib

D:\\SoftPath\\modelsim\\win64\\vmap xil_defaultlib msim/xil_defaultlib

D:\\SoftPath\\modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../CPU-Azathoth.srcs/sources_1/new" \
"sccomp_dataflow_oj_tb_func_synth.v" \
"../../../../CPU-Azathoth.srcs/sim_1/new/sccomp_dataflow_oj_tb.v" \


quit -force

