######################################################################
#
# File name : sccomp_dataflow_oj_tb_wave.do
# Created on: Thu Apr 26 02:02:44 +0800 2018
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
